version: "3.0"

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - es-net
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 2.2g

  logstash:
    container_name: ls-container
    image: docker.elastic.co/logstash/logstash:8.1.2
    environment:
      - ELASTIC_HOSTS=http://es-container:9200
    volumes:
      - ./requirements/logstash/data/to_ingest:/usr/share/logstash/data/to_ingest
      - ./requirements/logstash/config:/usr/share/logstash/config
      - ./requirements/logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - es-net
    depends_on:
      - elasticsearch
    entrypoint: [ "/bin/bash", "-c", "tail -f /dev/null" ]
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 1g

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1g

networks:
  es-net:
    driver: bridge
